version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: thumbnail_feedback
      MYSQL_USER: newuser
      MYSQL_PASSWORD: newpassword
    ports:
      - "3307:3306"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
